List<Map<String, dynamic>> mockupConsultaProdutosProdutos = [
  {
    'grupo': 'Auto Atendimento',
    'title': 'Fox Consulta',
    'code': 0,
    'price': 5.00,
    'img': 'fox-consulta-removebg-preview.png',
  },
  {
    'grupo': 'Auto Atendimento',
    'title': 'Fox Light',
    'code': 0,
    'price': 5.00,
    'img': 'fox-light-removebg-preview.png',
  },
  {
    'grupo': 'Auto Atendimento',
    'title': 'Fox Light com Dispensador de Gel',
    'code': 0,
    'price': 5.00,
    'img': 'fox-light-gel-removebg-preview.png',
  },
  {
    'grupo': 'Auto Atendimento',
    'title': 'Fox Pagamento',
    'code': 0,
    'price': 5.00,
    'img': 'fox-pagamento-removebg-preview.png',
  },
  {
    'grupo': 'Auto Atendimento',
    'title': 'Fox Senha',
    'code': 0,
    'price': 5.00,
    'img': 'fox-senha-removebg-preview.png',
  },
  {
    'grupo': 'Auto Atendimento',
    'title': 'Fox Teclado',
    'code': 0,
    'price': 5.00,
    'img': 'fox-teclado-removebg-preview.png',
  },
  {
    'grupo': 'Auto Atendimento',
    'title': 'Self Checkout',
    'code': 0,
    'price': 5.00,
    'img': 'Selfcheckout-removebg-preview.png',
  },
  {
    'grupo': 'Auto Atendimento',
    'title': 'Self Checkout Lumière',
    'code': 0,
    'price': 5.00,
    'img': 'Selfcheckout-lumiere-removebg-preview.png',
  },
  {
    'grupo': 'Auto Atendimento',
    'title': 'Terminal DUO',
    'code': 0,
    'price': 5.00,
    'img': 'termial-duo-removebg-preview.png',
  },
  {
    'grupo': 'Auto Atendimento',
    'title': 'Tower 32',
    'code': 0,
    'price': 5.00,
    'img': 'tower-32-removebg-preview.png',
  },
  {
    'grupo': 'Balanças',
    'title': 'Balança computadora linha DP',
    'code': 0,
    'price': 5.00,
    'img': 'balanca-removebg-preview.png',
  },
  {
    'grupo': 'Balanças',
    'title': 'Balança Eletrônica para Checkout DP 30CK',
    'code': 0,
    'price': 5.00,
    'img': 'balanca-30ck-removebg-preview.png',
  },
  {
    'grupo': 'Balanças',
    'title': 'Balança SM100',
    'code': 0,
    'price': 5.00,
    'img': 'balanca-sm100-removebg-preview.png',
  },
  {
    'grupo': 'Computadores',
    'title': 'Computador Touch Screen Aquiles',
    'code': 0,
    'price': 5.00,
    'img': 'computador-aquiles-removebg-preview.png',
  },
  {
    'grupo': 'Computadores',
    'title': 'CPU E3 Pico',
    'code': 0,
    'price': 5.00,
    'img': 'cpu-e3-pico-removebg-preview.png',
  },
  {
    'grupo': 'Computadores',
    'title': 'CPU Newera E3 Nano',
    'code': 0,
    'price': 5.00,
    'img': 'cpu-e3-nano-removebg-preview.png',
  },
  {
    'grupo': 'Computadores',
    'title': 'CPU Newera E3 Slim Fit',
    'code': 0,
    'price': 5.00,
    'img': 'cpu-e3-slim-removebg-preview.png',
  },
  {
    'grupo': 'Etiquetas Eletrônicas',
    'title': 'Etiquetas Eletrônicas',
    'code': 0,
    'price': 5.00,
    'img': 'etiqueta-removebg-preview.png',
  },
  {
    'grupo': 'Gaveta',
    'title': 'Gaveta para PDV',
    'code': 0,
    'price': 5.00,
    'img': 'gaveta-removebg-preview.png',
  },
  {
    'grupo': 'Impressoras de Etiquetas',
    'title': 'L42DT Impressora de etiquetas térmica',
    'code': 0,
    'price': 5.00,
    'img': 'L42DT-removebg-preview.png',
  },
  {
    'grupo': 'Impressoras de Etiquetas',
    'title': 'L42PRO Impressora de etiquetas desktop',
    'code': 0,
    'price': 5.00,
    'img': 'L42PRO-removebg-preview.png',
  },
  {
    'grupo': 'Impressoras Não Fiscais',
    'title': 'i8 Impressora térmica de cupom',
    'code': 0,
    'price': 5.00,
    'img': 'impressora-i8-removebg-preview.png',
  },
  {
    'grupo': 'Impressoras Não Fiscais',
    'title': 'i9 Full Impressora térmica de cupom',
    'code': 0,
    'price': 5.00,
    'img': 'impressora-i9-full-removebg-preview.png',
  },
  {
    'grupo': 'Impressoras Não Fiscais',
    'title': 'i9 Impressora térmica de cupom',
    'code': 0,
    'price': 5.00,
    'img': 'impressora-i9-termica-removebg-preview.png',
  },
  {
    'grupo': 'Leitores Fixos',
    'title': 'EL8600 - Leitor de Código de Barras fixo, 2D',
    'code': 0,
    'price': 5.00,
    'img': 'EL8600-removebg-preview.png',
  },
  {
    'grupo': 'Leitores de Mão',
    'title': 'BR-220 BT - Leitor de código de barras 2D portátil',
    'code': 0,
    'price': 5.00,
    'img': 'br-200-bt-removebg-preview.png',
  },
  {
    'grupo': 'Leitores de Mão',
    'title': 'EL250 - Leitor de Código de Barras de mão, 2D',
    'code': 0,
    'price': 5.00,
    'img': 'el-250-removebg-preview.png',
  },
  {
    'grupo': 'Leitores de Mão',
    'title': 'Flash - Leitor de Código de Barras de mão, 1D',
    'code': 0,
    'price': 5.00,
    'img': 'flash-1d-removebg-preview.png',
  },
  {
    'grupo': 'Leitores de Mão',
    'title': 'QuickScan - Leitor de Código de Barras de mão, 1D',
    'code': 0,
    'price': 5.00,
    'img': 'QuickScan-removebg-preview.png',
  },
  {
    'grupo': 'Módulos Fiscais',
    'title': 'Smart MFE',
    'code': 0,
    'price': 5.00,
    'img': 'sat-mfe-removebg-preview.png',
  },
  {
    'grupo': 'Módulos Fiscais',
    'title': 'Smart SAT',
    'code': 0,
    'price': 5.00,
    'img': 'smart-sat-removebg-preview.png',
  },
  {
    'grupo': 'Monitor E-TOUCH2',
    'title': 'Monitor E-Touch2',
    'code': 0,
    'price': 5.00,
    'img': 'monitor-e-touch2-removebg-preview.png',
  },
  {
    'grupo': 'PDV',
    'title': 'Computador Touch Screen Aquiles',
    'code': 0,
    'price': 5.00,
    'img': 'touch-screen-aquiles-removebg-preview.png',
  },
  {
    'grupo': 'PDV',
    'title': 'M8 MiniPDV',
    'code': 0,
    'price': 5.00,
    'img': 'm8-removebg-preview.png',
  },
  {
    'grupo': 'PDV',
    'title': 'M10 MiniPDV',
    'code': 0,
    'price': 5.00,
    'img': 'm10-removebg-preview.png',
  },
  {
    'grupo': 'Terminal de Consulta de Preços',
    'title': 'Terminal de consulta preços VP200',
    'code': 0,
    'price': 5.00,
    'img': 'fox-consulta-removebg-preview.png',
  },
];
